---
- name: deploy vm from template
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware
  vars_files:
    - secret.yml
  tasks:

    - name: Read JSON
      set_fact:
          vm_list: "{{ vm_list | from_json }}"

    - name: create VM folder
      vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter_name: "{{vcenter_datacenter}}"
        folder_name: "{{ create_folder_name }}"
        folder_type: vm
        state: present

    - name: deploy VM from template
      vmware_guest:
        hostname: "{{vcenter_hostname}}"
        username: "{{vcenter_username}}"
        password: "{{vcenter_password}}"
        validate_certs: "{{vcenter_validate_certs}}"
        datacenter: "{{vcenter_datacenter}}"
        #cluster: "{{vcenter_cluster}}"
        name: "{{item.split(',')[0]}}"
        folder: "{{create_folder_name}}"
        template: "{{create_template}}"
        state: "{{vm_state}}"
        hardware:
          memory_mb: "{{ram}}"
          num_cpus: "{{cpu}}"
        networks:
          - name: "{{vm_network}}"
            ip: "{{item.split(',')[1]}}"
            netmask: "255.255.255.0"
            gateway: "130.85.121.1"
      
      loop: "{{vm_list}}"
      loop_control:
        loop_var: item
      register: vm_deploy_results
     
    # - name: Change CPU and RAM
    #   community.vmware.vmware_vm_shell:
    #     hostname: "{{vcenter_hostname}}"
    #     username: "{{vcenter_username}}"
    #     password: "{{vcenter_password}}"
    #     validate_certs: "{{vcenter_validate_certs}}"
    #     cluster_name: "{{vcenter_cluster}}"
    #     vm_name: "{{create_vm_name}}"

    #     hardware:
    #       memory_mb: 4096
    #       num_cpus: 4

    
        
   
      
      

