- name: Find and copy package to remote machine
  hosts: localhost
 
  gather_facts: no
  vars:
    package_name: "apache2"  # Replace with the package name

  tasks:

    - name: Check if the package is installed on the local machine
      shell: dpkg-query -W -f='${Status}' {{ package_name }} | grep -q "install ok installed"
      ignore_errors: yes
      register: package_installed


    - name: Install the package if not already installed
      apt:
        name: "{{ package_name }}"
        state: present
      when: package_installed.rc != 0

    - name: Find the path of the package on the local machine
      find:
        paths: /var/lib/dpkg/info
        patterns: "{{package_name}}*.list"  
      register: package_path
      when: package_installed.rc == 0

- name: Install package on ubuntu20 machines
  hosts: 'crange1@133.228.78.3'
  become: true
  
  tasks:

    - name: Copy the package to the remote machine
      copy:
        src: "{{ item.path }}"
        dest: "/tmp"
      with_items: "{{ hostvars['localhost']['package_path'].files }}"

    - name: Install the package on the remote machine
      apt:
        deb: "/tmp/{{ item.path | basename }}"
        state: present
        allow_unauthenticated: yes
      with_items: "{{ hostvars['localhost']['package_path'].files }}"
