---
- name: Power on VM
  hosts: localhost
  gather_facts: false
  collections:
   - community.vmware

  vars_files:
   - secret.yml
  
  tasks:
   - name: Read json
     set_fact:
        machine_list: "{{ machine_list|from_json}}"
        
   - name: power on vm
     vmware_guest_powerstate:
        hostname: "{{vcenter_hostname}}"
        username: "{{vcenter_username}}"
        password: "{{vcenter_password}}"
        validate_certs: "{{vcenter_validate_certs}}"
        name: "{{item.split(',')[0]}}"
        state: powered-on
     loop: "{{machine_list}}"
     loop_control:
        loop_var: item
