- name: Install XRDP on ubuntu20 machines
  hosts: localhost

  tasks: 
    - name: Download libc6
      get_url:
         url: http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.35-0ubuntu3_amd64.deb
         dest: /tmp/libc6.deb
    - name: Download XRDP package
      get_url:
         url: http://archive.ubuntu.com/ubuntu/pool/universe/x/xrdp/xrdp_0.9.12-1_amd64.deb
         dest: /tmp/xrdp-package.deb

- name: Install XRDP on ubuntu20 machines
  hosts: '{{host_name}}'
  become: true
  
  tasks:
    - name: Transfer libc6 package to ub20
      copy:
         src: /tmp/libc6.deb
         dest: /tmp/libc6.deb

    - name: Transfer xrdp package to ub20
      copy:
         src: /tmp/xrdp-package.deb
         dest: /tmp/xrdp-package.deb
    
    - name: Install libc6 package
      apt:
         deb: /tmp/libc6.deb

    - name: Install xrdp package
      apt:
         deb: /tmp/xrdp-package.deb