---

- name: Remove Users
  hosts: '{{host_name}}'
  become: true
  gather_facts: false

  tasks:

  - name: Read CSV
    set_fact:
        user_list: "{{lookup('file',vars['csv_file_path']).split('\n')}}"

  - name: Remove Users
    user:
        name: "{{username}}"
        state: absent
        remove: yes
    delegate_to: "{{hostname}}"
    when: inventory_hostname == hostname
    vars:
        hostname: "{{item.split(',')[0]}}"
        username: "{{item.split(',')[1]}}"
    loop: "{{user_list}}"
    loop_control:
        loop_var: item
